# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    container.autowiring.strict_mode: true

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
        - { name: twig.extension }
        
    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Resources,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments', 'knp_paginator.injectable']

    AppBundle\Menu\Builder:
        arguments:
            $spotlightMenuItems: '%wphp.spotlight_menu%'
        tags:
        - { name: knp_menu.menu_builder, method: mainMenu, alias: main}
        - { name: knp_menu.menu_builder, method: searchMenu, alias: search}
        - { name: knp_menu.menu_builder, method: spotlightMenu, alias: spotlight}
        - { name: knp_menu.menu_builder, method: userNavMenu, alias: wphp_user }
        - { name: knp_menu.menu_builder, method: postNavMenu, alias: wphp_post }

    AppBundle\Repository\EnRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\En

    AppBundle\Repository\EstcMarcRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\EstcMarc

    AppBundle\Repository\FeedbackRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Feedback

    AppBundle\Repository\FirmRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Firm

    AppBundle\Repository\FirmroleRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Firmrole

    AppBundle\Repository\FormatRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Format

    AppBundle\Repository\GenreRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Genre

    AppBundle\Repository\GeonamesRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Geonames

    AppBundle\Repository\JacksonRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Jackson

    AppBundle\Repository\MarcSubfieldStructureRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\MarcSubfieldStructure

    AppBundle\Repository\MarcTagStructureRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\MarcTagStructure

    AppBundle\Repository\OrlandoBiblioRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\OrlandoBiblio

    AppBundle\Repository\OsborneMarcRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\OsborneMarc

    AppBundle\Repository\PersonRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Person

    AppBundle\Repository\RoleRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Role

    AppBundle\Repository\SourceRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Source

    AppBundle\Repository\TitleRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Title

    AppBundle\Repository\TitleSourceRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\TitleSource
